### ISSUE TITLE
Vignette to make permissions as clear as possible for the various fxns

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#102]

**Comment by butterflyskip** [comment]
Hi,
A total newbie here, a comp. sci student.  Would like to take a stab at this ... but will need some breadcrumbs to find my way around.

gracias

**Comment by sckott** [comment]
Hi @butterflyskip 👋   Thanks for stopping by. If you're still interested - are you new to R as well?  have you used the `devtools` package before?  Have you used `knitr` package?  Have you done a pull request on Github?  No problem if answer is No to all of these, can help you through it.

**Comment by butterflyskip** [comment]
Hi @sckott.  

Not totally new to R, but by no means an expert.  Yes, I have used the devtools package before, to download something from a github site.  I have not used the knitr package, yet.  And yes, I have done a couple of PRs, on github, but nothing merged yet :-(

**Comment by sckott** [comment]
There's a chapter on vignettes in the R pkgs book to help you get familiar with vignettes for R packages http://r-pkgs.had.co.nz/vignettes.html

After forking this repository to your github account, then pulling down to your machine, put the vignette file (with `.Rmd` file extension) in here: https://github.com/ropensci/fulltext/tree/master/inst/vign 

You can render a vignette (aka make markdown with text and output of any code, with file extension `.md`) by doing `knitr::knit("file-name.Rmd")`

As for the content of the vignette: I think we need an overview of what functions require users to need passwords or other permissions - and in what scenarios. For example, some publishers are totally open access, and never will require users to do anything special. Other publishers just require that a user be associated with an IP address that has access to their content. While still other publishers require a certain IP address range AND a password of some kind. I can help with these details as needed. 

questions?
