### ISSUE TITLE
Enhancement: EZproxy redirect for full text

### ISSUE THREAD

**Issue by andrewrech** [ropensci/fulltext#108]
Hello,

Thanks for developing this fantastic package!

Has anyone thought about implementing optional EZproxy re-direction for full text? If not, I will have a go at it.

This [database of EZproxy links](https://github.com/tom5760/ezproxy-db) could be used to create GET requests.

Thanks,
Andrew

**Comment by sckott** [comment]
@andrewrech thanks for the kind words.  don't think it's been considered here yet. can you explain a little about how EZproxy works and what it achieves (i've heard of it, but don't really know what it does)

**Comment by andrewrech** [comment]
[EZproxy](https://en.wikipedia.org/wiki/EZproxy) is a web proxy server used by many libraries, such as at my academic institution, to provide access to restricted full-text resources. URLs are re-directed to an EZproxy server that allows user authentication and then full-text access via the authenticated user's' library system.

It is pretty popular at academic libraries and access via this mechanism is integrated with many common ref management software.

An EZproxy library name, e.g. `University of Pennsylvania` and access credentials could optionally be provided with function calls to download protected full-text.

**Comment by sckott** [comment]
Thanks for the explanation @andrewrech 

Can this workflow be completely automated (maybe they use Oauth or so)? Or is there some manual step?

**Comment by andrewrech** [comment]
Hi @sckott,

I think, actually, this will be difficult to automate, as auth will need to follow the EZproxy server owners' protocol, which will differ in each case. So a web prompt would likely be required. So perhaps not a good fit for this package.

**Comment by sckott** [comment]
Maybe there are some auth protocols that are easier than others to deal with.  

When OAuth is used in R, it does open a web page and often requires user to click agree or so, so i think that is okay. 

Are there any example EZProxy setups to play with in R so we can get a sense for how this would go?

**Comment by andrewrech** [comment]
I don't think so.

If I want to access the full text of this [new](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature22047.html) article, 

`http://www.nature.com/nature/journal/vaop/ncurrent/full/nature22047.html`

gets redirected via EZproxy to 

`https://proxy.library.upenn.edu/login?url=http://www.nature.com/nature/journal/vaop/ncurrent/full/nature22047.html`

which prompts for my login credentials and then forwards to the full text.

So a authentication protocol-agnostic method would perhaps be to open a browser and save the resulting cookies for re-use during the session.

**Comment by sckott** [comment]
Okay, thanks. Still haven't really looked into this yet, will report back when I do

**Comment by sckott** [comment]
sorry for very long delay on this, getting out v1 of this pkg very soon - starting to get this on my radar (whether or not it can be addressed)

**Comment by sckott** [comment]
not happening
