### ISSUE TITLE
biorxiv_search() seems to only query the top page's articles, regardless of input limit

### ISSUE THREAD

**Issue by LucyMcGowan** [ropensci/fulltext#110]
When I run `biorxiv_search()` regardless of the limit I input, it only seems to return articles from the first page (the first 30), for example when I run:
```
search <- biorxiv_search(query = "ecology", limit = 30)
```
`search$data` it contains 30 unique articles. 

But if I bump the limit up to 40, `search$data` claims to contain 40 articles, but only 30 are unique.

```
sessionInfo()
## R version 3.3.3 (2017-03-06)
## Platform: x86_64-apple-darwin13.4.0 (64-bit)
## Running under: macOS Sierra 10.12.3
##
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] fulltext_0.1.8.9523
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.11          plyr_1.8.4            R.methodsS3_1.7.1    
## [4] R.utils_2.5.0         tools_3.3.3           digest_0.6.12        
##  [7] memoise_1.0.0         lubridate_1.6.0       jsonlite_1.5         
## [10] tibble_1.3.3          gtable_0.2.0          R.cache_0.12.0       
## [13] rcrossref_0.7.0       aRxiv_0.5.16          rlang_0.1.1          
## [16] bibtex_0.4.0          rstudioapi_0.6.0.9000 shiny_1.0.3          
## [19] DBI_0.5-1             crul_0.3.6            curl_2.6             
## [22] withr_1.0.2           dplyr_0.5.0           httr_1.2.1           
## [25] stringr_1.2.0         xml2_1.1.1            devtools_1.13.1      
## [28] rredis_1.7.0          grid_3.3.3            R6_2.2.1             
## [31] rentrez_1.1.0         XML_3.98-1.7          whisker_0.3-2        
## [34] solr_0.1.6            reshape2_1.4.2        ggplot2_2.2.1        
## [37] magrittr_1.5          rplos_0.6.4           scales_0.4.1         
## [40] htmltools_0.3.6       assertthat_0.2.0      mime_0.5             
## [43] xtable_1.8-2          colorspace_1.2-6      httpuv_1.3.3         
## [46] stringi_1.1.5         miniUI_0.1.1          lazyeval_0.2.0       
## [49] munsell_0.4.3         rjson_0.2.15          R.oo_1.21.0  
```
**edited to reflect actual problem**

**Comment by sckott** [comment]
thanks @LucyMcGowan 😸  - will get back to you soon on this 🐛

**Comment by LucyMcGowan** [comment]
thank you, @sckott! your emoji game is 💯🎉

**Comment by LucyMcGowan** [comment]
I think it might be [here](https://github.com/ropensci/fulltext/blob/master/R/bio_utils.R#L26-L36) - it doesn't pass `w`, it is passing just using `html` which I believe is just the response from the original pull (without the subsequent pages if limit > 30). The reason I was just seeing 6 (I think) is because I was doing a most recent pull and some of the DOIs haven't been registered for papers posted today.

**Comment by sckott** [comment]
there's still some weirdness going on, looking at it - not really a bug i think, will explain in a sec

**Comment by sckott** [comment]
changes in 26766c5500bacb75d4f74daaf75a601c879b2e0c 

@LucyMcGowan updated docs with date start and end params - and added description of why results are the way they are - let me know if it does or doesn't make more sense now

**Comment by LucyMcGowan** [comment]
👍 the `html` -> `w` was a bug though, yes?

**Comment by sckott** [comment]
Yes

**Comment by LucyMcGowan** [comment]
oh I see, you're clarifying why sometimes the output is < the input limit even if biorxiv finds them all (since it's querying crossref) - the updated docs make sense -- thank you @sckott! 🎉

**Comment by sckott** [comment]
Yes! thanks for the issue and the PR
