### ISSUE TITLE
Good Opportunity to work with ProQuest -- who should reach out?

### ISSUE THREAD

**Issue by nickbadams** [ropensci/fulltext#14]
ProQuest is looking for beta-users of a new Text and Data Mining Service (TDM). We may be interested in working with them. 

Who should reach out?

See email thread below.

Hi All,

I'm wondering if you can think of any faculty or grads who might be interested in taking part in ProQuest's early iteration of a Text and Data Mining (TDM) service? See the email below for details.

The corpus would initially include historical newspaper collections for which the Library has perpetual access licenses:
Chicago Defender (1910-1975)‎ 
Chicago Tribune (1849-1990)‎ 	
Los Angeles Times (1881-1990)‎ 	
The New York Times (1851-2010) with Index (1851-1993)‎ 	
San Francisco Chronicle (1865-1922)‎ 	
The Wall Street Journal (1889-1996)‎ 	
The Washington Post (1877-1997)‎ 
The Library is also considering purchasing licenses for about 30 other newspapers (I can send the list if you're interested) that would then be included in the TDM service. 

Let me know if you have any questions. 

best, 
Cody

---------- Forwarded message ----------
From: Karen Bosserman <Karen.Bosserman@proquest.com>
Date: Wed, Sep 10, 2014 at 7:24 PM
Subject: ProQuest Text and Data Mining Service
To: "jmckenzi@library.berkeley.edu" <jmckenzi@library.berkeley.edu>
Cc: "jdorner@library.berkeley.edu" <jdorner@library.berkeley.edu>, "lpeterse@library.berkeley.edu" <lpeterse@library.berkeley.edu>, Brad Roades <Brad.Roades@proquest.com>, Niels Dam <Niels.Dam@proquest.com>

Hello Jean:
Thank you for your patience while we gathered information surrounding our newest Text and Data Mining Service (TDM).  This is an exciting new model for us that we are actively seeking Launch partners and after you read more about this we are hopeful that you will consider partnering with us and being on the forefront of this latest research tool.  We will launch the first phase on October 1st.
 
The Text and Data Mining Service (TDM):
The first iteration is a web crawling facility that enables researchers (with the technical knowledge) to relatively easily access and download the OCR’ed text from the Newspapers in an XML format and then use this for research and educational  oriented TDM purposes – the dataset is as is and to be transparent that means varying quality of the OCR’ed text.
For Historic Newspapers(HNP) that Berkeley currently owns; and  has  Perpetual Access License (PAL)  year coverage for (e.g. NYT 1851 -1933 or for all the Black Historical Newspapers) a researcher can get access to the service at no additional charge. 
For non-Perpetual Access License years (1934 – 2010) for NYT there will be an additional content fee of $10,000.00; as well as an agreement based around using that data for a  specific identified project.
We will start the service based around our Historic Newspaper Collection (list attached) and build it out to include other PAL resources such as Periodical Archive Online (PAO) as well as our many products across the curriculum; pricing will be based on format and content extraction. For all other PQ content it is currently a more complicated process, but I’m happy to facilitate an enquiry to see if possible and if it is at what cost to the customer. In general we would only have rights to do for content sold as PALs content (with some exceptions).
From a launch partner we are looking to get feedback on what projects your researchers are doing (to learn use cases) as well as feedback on the service and ways we can improve it. Given that this is so new and still in large part a learning process for us the recommended engagement process is:
·        If there is a specific project in for using Historic Newspapers for TDM and you have researchers interested in Text and Data mining projects  we would like to set up a customer conference call to go through the service, clarification on legal issues as well ensuring that they have the technical capacity to utilize the service (for this service a certain level of experience with large gathering and manipulation of large data-sets is needed). It is not uncommon that we would first have a call with your library contact and then as a second step a call with the researcher who will utilize the service.
·        If there is agreement then the researcher would receive an e-mail with instruction on how to access the web crawling site that would enable them to systematically download the Historic Newspaper  in question within a specific time period (varies depending on the size of the dataset). Berkeley would then have a local copy of the data that can be saved and use for research and educational TDM purposes.
Best Wishes,
Karen
 
 
Karen Bosserman, Senior Account Manager
ProQuest |  Morro Bay, CA | 805 234 0011 | efax 805 221 6899
www.proquest.com
 
ProQuest… Start here. 2013 InformationWeek 500 Top Innovator

**Comment by sckott** [comment]
closing since I never heard back from them

**Comment by nickbadams** [comment]
I actually have news about this that just came in this week. But, closing
it is fine, because the news is bad: ProQuest has demoted the
priority-level of this project to focus on their quarterly bottom line,
which is being eroded by competition from EBSCO.



On Sun, Aug 9, 2015 at 9:19 AM, Scott Chamberlain <notifications@github.com>
wrote:

> Closed #14 <https://github.com/ropensci/fulltext/issues/14>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/fulltext/issues/14#event-377412669>.
>



-- 

Nick Adams

Data Science Fellow, Berkeley Institute for Data Science
<http://vcresearch.berkeley.edu/datascience/people>

Outreach Coordinator / Instructor / Consultant, D-Lab
<http://dlab.berkeley.edu/>

Principal Investigator, The Deciding Force Project
<http://www.decidingforce.com/>

**Comment by sckott** [comment]
@nickbadams thx for the update.  That's too bad!

**Comment by sarajohn840** [comment]
Mostly student asks online to write my dissertation for me so that my grades remain balanced.
https://www.customdissertation.co.uk/write-my-dissertation/
