### ISSUE TITLE
Question regarding VPN and proxy

### ISSUE THREAD

**Issue by andreifoldes** [ropensci/fulltext#160]
Greetings, I have the following question;

I want the package to harness my institutional access when I am working from home: meaning that I need VPN connection and automatic proxy. configuration when accessing articles via the browser.

Could this be done in R in such a way that fulltext can harness these parameters?

**Comment by sckott** [comment]
thanks for your question @andreifoldes  

- which function(s) are you using?  
- what version of `fulltext` are you using 

When I'm on my UC Berkeley VPN from home or elsewhere, I don't have to set proxy info, but i guess you're saying there's a VPN and proxy?.  Have you tried using `fulltext` through your VPN and proxy? Does it not work? What is the error message?

**Comment by andreifoldes** [comment]
Dear @sckott 

- I'd like to use ft_search, ft_abstract and ft_get in my project
- I'm working with fulltext_1.0.1.9141

In my case - don't know whether this is general or not - to access articles from home I am required both settings for manual browser based download:
1. https://www.lrz.de/services/netz/mobil/vpn/
2. https://www.lrz.de/services/netzdienste/proxy/browser-config/

My main issue: If I have the vpn On as per the instructions, I still only get XML files with with ft_get even though if I manually check the link in the XML files I could download the articles from my browser. So I assumed it has something to do with either/both vpn and proxy, right?

I did try extract the link from the xml and scrape the page - in case of ScienceDirect specifically - but no surprise the pdf url is not in the scrape.

Any advice would be much appreciated+

**Comment by sckott** [comment]
can you show me example code for just a few papers or so so I can make sure I know what code you're using and test out some things

**Comment by andreifoldes** [comment]
Sorry for the late reply.

So lets take the following example. 
1) I want to use ft_get() to download the following article:
https://www.sciencedirect.com/science/article/pii/S0010027716300063
2) My VPN and browser settings have been properly set according to the aforementioned links since I can download the article from my browser.
3) I run the following in R.
```
opts <- list(key = Sys.getenv('SCOPUS KEY'))
meta <- ft_get("10.1016/j.cognition.2016.01.006", cache=FALSE, scopusopts = opts) 
```
4) Alas, when looking at the XML in the cache folder, there is nothing resembling fulltext.

Thank you - I can send you my university access details in private if necessary.

**Comment by sckott** [comment]
Sorry for the long delay on this. 

What you get with that example I imagine, and what I get without my VPN on, is just the abstract. 

When I turn on my VPN I get the full text. 

What I think you are missing is your Crossref TDM token. You might be able to use a specific Scopus api key too, but lets try the Crossref TDM token route first. For docs see the _Crossref TDM_ section of the _Authentication_  section of the manual page at `?fulltext`

Go to https://apps.crossref.org/clickthrough/researchers and login with your ORCID id. Then you agree to terms and get a token. I think you can only sign up for Wiley and Elsevier. 

With your key see the _Crossref TDM_ section referenced above for how to use it. 

With that key you should get full text now. 

A little tip is you can do the request like 

```r
ft_get("10.1016/j.cognition.2016.01.006", verbose = TRUE)
```

to see the HTTP request headers that are sent where if you set it up right, you'll see your TDM token in the header like:

```
> GET /content/article/PII:S0010027716300063?httpAccept=text/xml HTTP/1.1
Host: api.elsevier.com
User-Agent: libcurl/7.54.0 r-curl/3.3 crul/0.7.0
Accept-Encoding: gzip, deflate
CR-Clickthrough-Client-Token: some-alphanumeric-string
Accept: text/xml
```

let me know if that works

**Comment by marco86to** [comment]
Hello,
my institution use a proxy based system to access to the full texts...
Is there a way to set proxy url, port, user and password in order to be able to download the full text of the publication?

`ft_get('10.1016/j.gie.2017.03.1542') `
returns:
`<fulltext text>
[Docs] 0 
[Source] ext - C:\..../R/fulltext 
[IDs] 10.1016/j.gie.2017.03.1542 ... 
Warning messages:
1: In readLines(w) :
  incomplete final line found on 'C:\...../R/fulltext/10_1016_j_gie_2017_03_1542.xml'
2: you may not have access to 10.1016/j.gie.2017.03.1542
 or an error occurred
 or the downloaded file was invalid `

If I go to the page of the article: https://linkinghub.elsevier.com/retrieve/pii/S0016-5107(17)31780-7 by my browser behind the proxy I can download the article.

Thanks
Marco

**Comment by sckott** [comment]
thanks for your question @marco86to 

this should be possible. See `?proxies` and `?crul-options` after loading `library(crul)` . The `crul`  pkg is the underlying http package. 

This should work but I can't test it under your particular situation of course:

```r
library(fulltext)
library(crul)
set_proxy(proxy("http://97.77.104.22:3128"))
ft_get('10.1016/j.gie.2017.03.1542') 
```

You can set other details for your proxy with the `proxy` function

**Comment by behrica** [comment]
I just proposed to add an example to show how to use a authenticated proxy, which worked for me.
See here #220

Maybe it works as well with "set_proxy", but I have not tried that.

**Comment by sckott** [comment]
thanks, will have a look @behrica
