### ISSUE TITLE
Question concerning ft_get function and entrez_search

### ISSUE THREAD

**Issue by t088** [ropensci/fulltext#167]
Hello I am new to this field, so please excuse my probably trivial question:

I searched for the term political extremism in pmc and wanted to pass the output to the ft_get function to get the full text  and thereafter extract text chunks such as the body and author.

```
query <- "political extremism OR violent extremism"
(res <- ft_search(query, from = 'entrez', limit = 200))
(out <-ft_get(res)) 
out%>%ft_collect()%>%ft_chunks(c("title", "body", `"authors"))%>%ft_tabularize()`
```

Unfortunately, the ft_get function returns an error:
"Error: These are probably not DOIs:
NA
NA
....."
(I am using fulltext_1.0.1 version)

I would very much appreciate if you could help me out!
Many thanks!
Cheers

**Comment by sckott** [comment]
thanks for the issue @t088 - on vacation now, will respond mid next week

**Comment by sckott** [comment]
@t088 pushed a fix, can you reinstall and try again

**Comment by sckott** [comment]
fixed, closing
