### ISSUE TITLE
fulltext data structure

### ISSUE THREAD

**Issue by emhart** [ropensci/fulltext#2]
I wanted to begin the discussion of data structures for the data that's returned.  Here's a list of ideas.

1. Should text be automatically converted to a `tm` corpus or just stay as plain text?
2. Should data be written to disk and then read back in via `tm`?  Or perhaps this is an option
     * If it's written to disk, what format should be used?  Plain text? XML?
3. What's happening with metadata?  
     * Is it / How is it attached to the data?
     * Should it be written to disk?
          * If so what format?  DC?  DataCite?
4. Should we include other metadata elements?
    * When did the search occur?
    * What were the query parameters?
5. If we decide to write to disk, could we embed metadata and the data as a single XML (or JSON) document?
6.  If we consider JSON, what about a CouchDB interface for fulltext?  

I'm sure there's other things I haven't thought about too.

**Comment by sckott** [comment]
This is more or less set now I think, we can open new issues as needed to change the data structure
