### ISSUE TITLE
adding biorxiv to plug in structure of the pkg.

### ISSUE THREAD

**Issue by emhart** [ropensci/fulltext#20]
The approach you're using with plug-ins seems to require that each source is its own package.  I wanted to add the biorxiv search code in now that pdf extraction is an option. Should I just make it it's own small package and push to CRAN to keep with your overall structure? Or do you think there's room for sources to be internal to the package (I can see why this should be avoided though)?

**Comment by emhart** [comment]
No word so closing and nuking.

**Comment by sckott** [comment]
sorry i didn't get back to you :( - looks like your fork is gone - do you still have it locally?  would be good to get it rolled in - in terms of where to put PDFs, i went with a hidden folder in the user's root directory https://github.com/ropensci/fulltext/blob/master/R/cache.R#L21 - but been trying to build in different options for caching pdfs, so path to store things is only relevant with one of the backend options

**Comment by sckott** [comment]
can we reopen?

**Comment by sckott** [comment]
@emhart

**Comment by emhart** [comment]
biorxiv is now it's own package: https://github.com/emhart/biorxiv, I can refork and add my old code in for searches and send a PR.

**Comment by sckott** [comment]
@emhart cool, sounds good

**Comment by emhart** [comment]
Search functionality is all up to snuff if you want to merge with master.  It looks like a lot of commits because the old biorxiv branch had fallen way behind, but when merged into master it should just have a few actual changes.  

Still todo:
- [ ] Add plug-in to `ft_get()` 

What's the best way to do this @sckott ? Looks like all the other classes return full text as ascii and store in your class `ft_data()`.  I can return the abstracts and store them in `ft_data` and download the PDF's to the cache directory.  I can just return a message saying "your pdf's have been downloaded too..."  Let me know what your ideal work flow is and I can implement it.

**Comment by sckott** [comment]
@emhart 

Right now 

```r
(res <- ft_get('10.1371/journal.pone.0086169', from='plos'))
#> [Docs] 1 
#> [Source] R session  
#> [IDs] 10.1371/journal.pone.0086169 ... 
```

indexing to plos gives

```r
res$plos
#> $found
#> [1] 1
#> 
#> $dois
#> [1] "10.1371/journal.pone.0086169"
#> 
#> $data
#> $data$backend
#> NULL
#> 
#> $data$path
#> [1] "session"
#> 
#> $data$data
#> 1 full-text articles retrieved 
#> Min. Length: 111132 - Max. Length: 111132 
#> DOIs: 10.1371/journal.pone.0086169 ... 
#> 
#> NOTE: extract xml strings like output['<doi>']
#> 
#> $opts
#> $opts$doi
#> [1] "10.1371/journal.pone.0086169"
#> 
#> $opts$callopts
#> list()
```

so there's not really a spot to store abstracts, but that's something we could consider. Problem is if we're downloading pdfs, then we have to extract the abstract for all articles on the call to `ft_get()`, which could take a long time if there's lots of articles. And some may not have abstracts, etc. 

I've moved to by default pushing data to disk instead of storing in R memory, then user has to make separate call to read in the data - all to try to avoid problems at scale if a user e.g., retrieves 10K articles.

**Comment by emhart** [comment]
Ahhh, ok...

Actually because the biorxiv site stores abstracts as text, I just scrape that and store it so that's why I thought I could update it.  I'll work on this with your new changes.
