### ISSUE TITLE
ft_get() for PLOS returns XML only

### ISSUE THREAD

**Issue by clbti** [ropensci/fulltext#205]
Hi, even though I specified the type as "PDF" in getting the full text and the file downloaded from PLOS is indeed in "PDF" format, but the file downloaded itself cannot be opened as PDF. It can only be opened with software compatible with XML. Attached is an example of the file.

```r
ft_get("10.1371/journal.pcbi.0010019", from = 'plos', type="pdf")
```

Did I use the function incorrectly?

Thanks

[10_1371_journal_pcbi_0010019.pdf](https://github.com/ropensci/fulltext/files/3450929/10_1371_journal_pcbi_0010019.pdf)

**Comment by sckott** [comment]
R session info please, as requested

**Comment by sckott** [comment]
reinstall and try again, should work now

**Comment by clbti** [comment]
Many thanks Scott. Yes, it works now!
