### ISSUE TITLE
Query exact phrase using ft_search

### ISSUE THREAD

**Issue by kristenpeach** [ropensci/fulltext#228]
I want to find publications that include my complete query phrase. The link from the package help page (https://dev.elsevier.com/sc_search_tips.html) says I need to use brackets to do this: "To find documents that contain an exact phrase, including any stop words, spaces, and punctuation, enclose the phrase in braces: {oyster toadfish}." But when I try to use brackets in my query the code won't run. Any suggestions?

This code chunk runs fine but it returns some publications that do not include an exact match to my search phrase:

`res1 <- ft_search(query = "complete phrase here", from=c('plos','crossref','arxiv', 'biorxivr', 'europe_pmc', 'ma'), limit = 1000)`

This does not run:

`res1 <- ft_search(query = {complete phrase here} , from=c('plos','crossref','arxiv', 'biorxivr', 'europe_pmc', 'ma'), limit = 1000)`

error: Error: unexpected symbol in "res1 <- ft_search(query = {complete phrase"

Any guidance would be appreciated!

**Comment by sckott** [comment]
Thanks for your question!

Try the `ft_search` query again, but this time put the entire thing in quotes: `"{complete phrase here}"`

**Comment by kristenpeach** [comment]
Thanks for the quick response! That produces this error: 

Error: 400 - org.apache.solr.search.SyntaxError: Cannot parse '{complete phrase here}': Encountered " <RANGE_GOOP> "phrase "" at line 1, column 8. Was expecting: "TO" ...

**Comment by sckott** [comment]
the docs for `ft_search` say

> See https://dev.elsevier.com/sc_search_tips.html for help/tips on searching with Scopus

So that link is only for help when searching `scopus`

That new error is coming from plos, so you can just not include that source. 

In addition, make these changes:

- `biorxivr` should be `biorxiv`
- `europe_pmc` should be `europmc ` 
- `ma` should be `microsoft`

**Comment by kristenpeach** [comment]
Thank you!!!
