### ISSUE TITLE
the "limit" argument doesn't get overridden by the "limit" or "count" argument passed in a list options to the ft_search function

### ISSUE THREAD

**Issue by vipulg13** [ropensci/fulltext#229]
Dear Team,

first of all, thanks for this incredible one shot interface. 

As I stated in the title field, it would be great if you could make a necessary changes in your plugins functions, such that if the limit or count argument is passed in the list options specific to the data source, then it gets precedence over the function level "limit" argument. This will provide great flexibility to the user, as the user can set the values for different data sources in a preferential manner and get the desirable results through a single function call.

Let me know if you need further details from my side.

Regards,
Vipul

**Comment by sckott** [comment]
Thanks for the issue. I'll have a look

**Comment by sckott** [comment]
@vipulg13 should work now, reinstall  `pak::pkg_install("ropensci/fulltext")`

**Comment by vipulg13** [comment]
@sckott it is now working as expected. 
Just a small note: you could also consider making a slight change in the plugin_search_crossref(...) module to get rid of below warning-

Warnmeldung:
`tbl_df()` is deprecated as of dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.

**Comment by sckott** [comment]
great, glad it works. thanks for the note

**Comment by sckott** [comment]
the warning comes from a dependency - not sure which one, possibly from rcrossref, but if that pkg then its an older version of it as the current version doesn't use tbl_df anywhere
