### ISSUE TITLE
Use case: search for pesticide names

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#23]
From G-group mailing list  https://groups.google.com/forum/#!topic/ropensci-discuss/T5aPR8e9RYc

> I would like to do large scale pesticide research using your package. I have lists of pesticides that I would like to use to accumulate information from open source journals. Since each pesticide is known by multiple names I have other tables to lookup synonyms and commercial names, etc.  What workflow do you suggest to use your package to search for a term such as "atrazine" occurring in your suite of open source journals? I would like the paper as PDF, the full text to send to tm or downstream NLP software, and I would also like a list of occurrences as DOIs, so that I can list results in a table with the DOI. A single list can have ~2,000 pesticide compounds. When we consider the several synonyms that may be standardized chemical nomenclature (IUPAC), commercial names, short names, etc, this inflates the search space to 8x-20x searches per compound.

**Comment by maelle** [comment]
It'd pair well with https://github.com/ropensci/webchem

**Comment by sckott** [comment]
good idea!
