### ISSUE TITLE
problem working through examples in fulltext manual

### ISSUE THREAD

**Issue by banderson10** [ropensci/fulltext#230]
Hello,
I have been working through the examples in the fulltext manual in the last several days. Today (Thursday December 17), when I try to just run a simple example like the following that is in Chapter 9 (Fetch), I get an HTTP error. The example and error is below.

From Chapter 9 (section 9.3) in the fulltext manual:

Code:
(res <- ft_get('10.1371/journal.pone.0086169'))

Error in Console:
Error: Bad request (HTTP 400)

I tried the examples using my RStudio Cloud account and on my local R install. Any suggestions would be appreciated! The example code had been working fine in the past several days.

Thank you!

Billie

**Comment by banderson10** [comment]
Hi again,
Please disregard my previous message. I just logged into RStudio again, and now the example code is running with no errors! Apologies for the 'false alarm'. I have learned a lot about this package from the manual! I am looking forward to applying fulltext() to my team's research problem.
Billie

**Comment by sckott** [comment]
Great, glad its working again. A 400 series HTTP error https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400 is a "client error" - or what's perceived to be a client error (client here refers to the fulltext package). But, servers don't always give the right http status code, so its possible it was a problem on the PLOS side (that's a PLOS DOI). I've noticed that PLOS has been having some problems lately, so its likely a problem on their side
