### ISSUE TITLE
ft_get() is unable to retrieve data from the scientific.net publisher

### ISSUE THREAD

**Issue by vipulg13** [ropensci/fulltext#232]
Hello Team,

until last week the ft_get() was able to fetch articles from the "scientific.net" publisher using the default settings i.e., through the crossref gateway, however, from this week onwards I am not able to fetch the data. I have checked the institutional access and I am able to manually download fulltext pdfs directly from the www.scientific.net and Scopus. 

The problem appears to be related with the termination of Crossref TDM clickthrough service. 

An exemplary call to reproduce the problem could be: ft_get("10.4028/www.scientific.net/amm.130-134.1062")
Earlier this call led to the download of a pdf file. Now, it returns nothing. Furthermore, the call with similar dois is causing a response super slow. All I could diagnosed is that the mechanism is keeping the empty pdf files for a longer period (more than a minute) and trying to fetch the data corresponding to them. Despite enabling parallel processing with 12 cores, the ft_get() call turns out to be laggy, which it was definitely not before.

Could someone look into this issue?

Let me know in case you require further details.

Thanks in advance!

**Comment by sckott** [comment]
Thanks for the report 

I'm aware of the issue https://github.com/ropensci/fulltext/issues/224 - Yes Crossref TDM is gone, and you now have to get your own keys for Elsevier and Wiley. Will be making changes soon

**Comment by vipulg13** [comment]
Hi @sckott, thanks for the prompt check and comment.

The Elsevier key has already been set into the .REnviron. For Wiley, I could see that my research institute has access to the online library. I tried exploring the Wiley and further created an account but it is still unclear to me how to generate a key. 

Anyway, I wait for further instructions.

Thanks again!

**Comment by sckott** [comment]
For a Wiley token, they just got their TDM program released - https://onlinelibrary.wiley.com/library-info/resources/text-and-datamining I've got a token but haven't tested it yet

**Comment by vipulg13** [comment]
@sckott : thanks for sharing it. I have also got a token. 
But, I am still sceptical about the retrieval of full text articles from the "scientific.net" publisher because I am largely missing articles at the moment from this particular publisher only. Let's see how the system works after the new changes. Maybe the "scientific.net" publisher is implicitly incorporated in the Elsevier service.

**Comment by sckott** [comment]
@vipulg13 reinstall `remotes::install_github("ropensci/fulltext")`, then try 

```r
library(fulltext)
library(rcrossref)
x <- cr_members(2457, works=TRUE, filter = list(type = "journal-article"))
x$data$doi[1:5]
z <- ft_get(x$data$doi[1:5])
z$transtech
```
