### ISSUE TITLE
Hi, I am a new user and need setting up the API for BMC. Could you please provide the code for setting BMC API in R. 

### ISSUE THREAD

**Issue by datalake101** [ropensci/fulltext#241]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by Rekyt** [comment]
Hey @datalake101, I'm not the maintainer of the package but I can answer you.

To get the API running for BMC you can follow what's written there: https://docs.ropensci.org/fulltext/reference/fulltext-package.html#authentication

> BMC: BMC is integrated into Springer Publishers now, and that API requires an API key. Get your key by signing up at https://dev.springer.com/, then you'll get a key. Pass the key to a named parameter key to bmcopts. Or, save your key in your .Renviron file as SPRINGER_KEY, and we'll read it in for you, and you don't have to pass in anything.

So what you need to do is:

1. Signup at https://dev.springer.com/,
2. Get a key.
3. Copy this key and store it as an `.Renviron` file as a `SPRINGER_KEY` variable.

If this last step sounds confusing, this means create an `.Renviron` text file at the root of your project that contains:

```
SPRINGER_KEY=<<your_key>>
```

with `<<your_key>>` replaced by the value you obtained at Step 2.

**Comment by sckott** [comment]
thanks for the help on this @Rekyt !

**Comment by maelle** [comment]
This repository is about to be archived.
If you develop a related package, it might be in scope for https://ropensci.org/software-review/
