### ISSUE TITLE
Gone from CRAN?

### ISSUE THREAD

**Issue by LukasWallrich** [ropensci/fulltext#243]
I am sure you are aware of that, but fulltext is gone from [CRAN](https://cran.r-project.org/web/packages/fulltext/index.html). 

Before figuring that out, I tried a few other ways of making install.packages work, including updating R and all packages ... so an update to the README would be a helpful interim step. 

Hope you can get this back to CRAN without too much hassle.

**Comment by sckott** [comment]
hi @LukasWallrich tldr: it won't be going back on cran. 

i've moved on to another job and no longer work on this pkg, and could not find someone else to take it over. if you're interested, let me know. You should be able to install from github like `remotes::install_github("ropensci/fulltext")`, or r-universe - see https://ropensci.r-universe.dev/ui#builds

**Comment by LukasWallrich** [comment]
Thanks for that update! I don't feel that I have the expertise/experience to maintain this package - if there is someone else I could share it with (whom you know, or who might just read this), I'd be happy to think about it.

**Comment by sckott** [comment]
Don't know of any others interested.

**Comment by maelle** [comment]
This repository is about to be archived.
If you develop a related package, it might be in scope for https://ropensci.org/software-review/
