### ISSUE TITLE
fulltext use cases

### ISSUE THREAD

**Issue by emhart** [ropensci/fulltext#3]
What are usecases for fulltext?  
* Mining scholarly full text data or metadata for when terms arise.  [Here's a good example](https://github.com/ropensci/rentrez/blob/master/README.md)  from the `rentrez` README

**Comment by sckott** [comment]
> Another possible use case for fulltext could be to load tables and supplementary material in tabular form into R.

taken care of (i think) in `ft_get_si()` now

**Comment by dwinter** [comment]
Hi @sckott , thought you might like to see a use case "in the wild". Using `ft_get_si()` in a reproducible workflow/example for `rotl` that we hope to reference in an MS about that package: 

https://github.com/ropensci/rotl/blob/meta_analyses_eg/vignettes/meta-analysis.Rmd

**Comment by sckott** [comment]
@dwinter awesome! Thanks. Any thoughts on how it could be better

**Comment by dwinter** [comment]
Thanks to you and @willpearse for creating it -- a really helpful addition. 

The only tiny snag I hit was the `readxl::read_excel` guesses file type by name (and you can't specify it format argument and the lower-level functions for each type aren't exported) . I don't know if it's possible, but if the file-path-like object returned by `ft_get_si` could maintain the extension that might be helpful. (Though the work-around of specifying the `save.name` is no great problem)

**Comment by willpearse** [comment]
Thanks - this is useful to know, and I'll fix this in the next update. Great to know this is actually being used in the wild :D

We've discussed something similar to this, which I've written (but not merged) a solution to, so it should appear very soon. Thanks again!!!

**Comment by sckott** [comment]
Thanks for the feedback @dwinter

**Comment by sckott** [comment]
closing, open issues for individual use cases
