### ISSUE TITLE
add support for Stanford Parser

### ISSUE THREAD

**Issue by karthik** [ropensci/fulltext#30]
http://nlp.stanford.edu/software/lex-parser.shtml

via Nick Adams

**Comment by sckott** [comment]
@karthik will this introduce a Java dependency?

**Comment by karthik** [comment]
Unfortunately yes. But apparently it is quite popular. So we'll have to
discuss it more.

**Comment by sckott** [comment]
hopefully we can do this in a way that the java dep is optional

**Comment by karthik** [comment]
We can't make it work with Java as optional. One will need Java anyway to install the parser locally. We don't introduce any additional dependencies on our side. We can use rJava to work with this API, but rJava will install easily because Java would already exist locally for the parser to work.

**Comment by sckott** [comment]
@mbjones thoughts on this?  Any way to avoid a `rJava` dependency?

**Comment by sckott** [comment]
seems out of scope now that the pkg is more mature - this is something users may want to do downstream of course, but i don't think we want to import here
