### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by Ackhuman** [ropensci/fulltext#37]
I've been using this tool for a few days and it seems to work fine so far, but I am now getting an error when I try to "ft_search":

    Error in function (type, msg, asError = TRUE)  : Empty reply from server

I have tried several search terms, including ones that previously worked correctly and the one that's used in the example usage ("ecology").  Is there some API limit I have hit, maybe, or is the tool somehow doing something wrong?

**Comment by sckott** [comment]
hi @Ackhuman - thanks for the report. 

Can you give examples that gave that error?

**Comment by Ackhuman** [comment]
Hmm, I'm on a different network than before from this morning and it now seems to be working.  The problem may have just been a firewall issue.  Here is a sample:

> ft_search("agroecology")
Error in function (type, msg, asError = TRUE)  : Empty reply from server
> ft_search("agroecology", from="plos")
Error in function (type, msg, asError = TRUE)  : Empty reply from server
> ft_search("ecology", from="plos")
Error in function (type, msg, asError = TRUE)  : Empty reply from server

But it now seems to be working fine

> ft_search("ecology", from="plos")
Query:
  [ecology] 
Found:
  [PLoS: 27832; BMC: 0; Crossref: 0; Entrez: 0; arxiv: 0; biorxiv: 0] 
Returned:
  [PLoS: 10; BMC: 0; Crossref: 0; Entrez: 0; arxiv: 0; biorxiv: 0]

**Comment by sckott** [comment]
Yeah, most likely PLOS (the default data sources in that fxn) service was temporarily down and now it's back up

**Comment by sckott** [comment]
@Ackhuman everything's good now?

Keep letting us know of other problems, feature requests!

**Comment by Ackhuman** [comment]
Yes, I'm guessing it was a problem with the network since going to a different network fixed the issue.  I suppose there would be no easy way to detect that this was happening, either.

**Comment by sckott** [comment]
Yeah, that's sometimes hard to tell - but usually an `Empty reply from server` means the remote server is down, and hopefully temporarily.  I think if the network you are on is causing the problem, I think you'd get an error more like `Couldn't connect to server`
