### ISSUE TITLE
fulltext sources

### ISSUE THREAD

**Issue by emhart** [ropensci/fulltext#4]
What sources should we include in `fulltext`?  Currently we have:
- `rplos`
- `bmc` 
- `elife` 

for fulltext.  We should also be able to get fulltext from F1000 via RSS, and I'm not sure about PeerJ.

We can also get metadata for most pubmed papers via `rentrez` and we can get metadata access to arxiv papers: http://arxiv.org/help/bulk_data

What sources are we missing?

**Comment by sinandrei** [comment]
Scopus provides full-text api for Science Direct with api keys. Would you consider including that?

**Comment by sckott** [comment]
@sinandrei we have included Scopus now, see `ft_abstract`, `ft_search`, and `ft_get`

**Comment by sinandrei** [comment]
@sckott indeed. cool!. Am I right in thinking that the chunking for the elsevier material is not yet implemented?

**Comment by sckott** [comment]
what do you mean by chunking?

**Comment by sinandrei** [comment]
the x %>% chunks("publisher") %>% tabularize() type syntax did not return
any values for my elsevier type ft_gets()

**Comment by sckott** [comment]
can you open a new issue with a reproducible example. this is getting off topic of this issue
