### ISSUE TITLE
Vignette with examples for lots of diff. publishers/journals

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#46]
so users can see their specific journal they're interested in

**Comment by pkraker** [comment]
This would be very helpful. The MWE for searching and retrieving seems to be working only for PLOS.

    (res1 <- ft_search(query = 'ecology', from = [source])
    (out <- ft_get(res1))

**Comment by sckott** [comment]
Okay, will try to get this done soon. 

@pkraker  Can you open issues with the problems you run in to?

**Comment by pkraker** [comment]
@sckott Thanks, will do!
