### ISSUE TITLE
Visualizations

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#5]
- [ ] Would be great to use @cpsievert work on interactive topic model visualization here - perhaps we can import https://github.com/cpsievert/LDAvis - thoughts Carson?

* What are other common types of vizualizations for exploring text

**Comment by sckott** [comment]
This pkg is complex enough that if we do viz, I think it belongs in a diff. package

**Comment by karthik** [comment]
:+1:

**Comment by sckott** [comment]
closing
