### ISSUE TITLE
Make plugins for Europe PMC

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#52]
this is separate from Entrez and PMC US

p.s., would also do Canada PMC, but they look a bit haggard

**Comment by sckott** [comment]
related to #4

**Comment by sckott** [comment]
docs at https://europepmc.org/RestfulWebService

**Comment by willpearse** [comment]
FWIW I've got this working for SI downloads now (...on my fork) which I'll PR once I've done a few other things...

**Comment by sckott** [comment]
:+1: sounds great

**Comment by sckott** [comment]
good for now, have in `ft_search` - could add to `ft_get`/others possibly, but can come back to that if users request
