### ISSUE TITLE
More helpful error for pdfx

### ISSUE THREAD

**Issue by soodoku** [ropensci/fulltext#53]
Dear Scott,

pdfx gives a very unhelpful error. It would be nice to rewrite the function so that we have a better handle of where the process went wrong.

e.g. 
pdfx(file = "PA_Casey_Auditor_General.pdf")
Error: something's wrong

**Comment by sckott** [comment]
thx for the report, taking a look

**Comment by sckott** [comment]
@soodoku are you sure the path to the file is correct?  Can you email me the pdf

**Comment by soodoku** [comment]
Dear Scott,

The path is correct. But the file itself is an 'unsearchable pdf' (so just a static image hiding as pdf). Obviously, ghostview, xpdf etc. all fail miserably in getting any data out of it. (And they aren't designed to get any data out). Link to pdf:
https://github.com/soodoku/abbyyR/blob/master/inst/extdata/wisc_ads/PA_Casey_Auditor_General.pdf

But the suggestion I had was for more helpful error for pdfx. It would just be good to have an error that is other than 'something's wrong'. Windows 10 was heavily panned by Apple users for an error that said 'something happened'. Link to some article with a screenshot of the error:
http://www.askvg.com/fix-something-happened-error-message-in-windows-10-upgrade/

**Comment by sckott** [comment]
@soodoku thanks, I'll look into the pdfx API and see if they are returning helpful messages that I don't pass to user. if not, i'll see if I can check the pdf to see if it's one that pdfx will parse correctly.
