### ISSUE TITLE
Better documentation for windows

### ISSUE THREAD

**Issue by soodoku** [ropensci/fulltext#54]
Dear Scott,

For windows, it would be good to add directions for xpdf and ghostscript. 
They amount to two things.
1. Download X from XYZ
2. Set the PATH variable in 'environment variable' to the directory containing the xpdf executables (there are a bunch.)

Adding the two to readme is likely to make it easier for people to use the package.

**Comment by sckott** [comment]
@soodoku added a new checker to `ft_extract()` so should tell user if they don't have ghostscript or pdftotext installed.  Added text to readme and a new man file (`?extract_tools`).  I couldn't yet find exact instructions on how to set path variables on windows. Do you know?

**Comment by soodoku** [comment]
Dear Scott,

Apologies for being cryptic earlier.

Re. how to set PATH variable in environment variables, this should prove useful:
http://www.computerhope.com/issues/ch000549.htm

More generally: PATH variable defines the search space. So when it comes across gs or xpdf command, it looks into the search space to find executables related to that. 

Typically, path amendments will be: 
C:\Program Files\xpdf\  (the person will need to inflate the zip file and then dump the exes in that directory.)
and
C:\Program Files\gs\gs9.16\bin\  (for ghostview)

**Comment by sckott** [comment]
closing this b/c just using `pdftools` internally now
