### ISSUE TITLE
ft_get seems to not work for 'arxiv' (on WinXP)

### ISSUE THREAD

**Issue by justa9** [ropensci/fulltext#56]
Hey!

Following along the vignette examples, I tried this:

```
library("fulltext")
res <- ft_get('cond-mat/9309029', from = "arxiv")
```

But it resulted in the following error:

```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) :
  Failed to open file C:\Documents and Settings\justa9\Rhome\.fulltext\cond-mat_9309029.pdf.
```

A network dump shows that when 'arxiv' is used then no network packet is sent anywhere.
On the contrary, all other 'from' options communicate (and return the aproppriate data) normally.

Tried both CRAN and latest development version of this package, but the error is the same.

**Comment by sckott** [comment]
@justa9 thanks! I'll have a look

**Comment by sckott** [comment]
@justa9 can you try it again, i started to try on my windows xp virtual box, but ran into some problems and gave up, but should work

**Comment by justa9** [comment]
It works now!

Thanks again!

**Comment by sckott** [comment]
great!
