### ISSUE TITLE
Issue with Solr and Loading

### ISSUE THREAD

**Issue by abresler** [ropensci/fulltext#58]
Trying to recreate the demo from the cran install and I get this issue 

```
library(fulltext)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘solr’ 0.1.9.99965 is being loaded, but <= 0.1.4 is required
Error: package or namespace load failed for ‘fulltext’
```

Any idea how to fix?

**Comment by sckott** [comment]
@abresler thanks for the report. 

`rplos` https://github.com/ropensci/rplos/blob/master/DESCRIPTION#L36  used in this pkg requires `solr` < a certain version b/c I'm doing a reworking of `solr`  that would break things in `rplos`, so I wanted an easy way to force people to have a compatible `solr` version. 

fix is to just install the current cran version of `solr` 

I'll get the next `solr` version up soon, and this will go away

**Comment by sckott** [comment]
@abresler let me know if that works

**Comment by abresler** [comment]
Works like a charm, thank you sir

**Comment by sckott** [comment]
great :rocket:
