### ISSUE TITLE
Take a look at tesseract

### ISSUE THREAD

**Issue by abresler** [ropensci/fulltext#59]
Not sure if this fits the mission of this package but Duncan Templeton Lang has a nice package that leverages Tesseract for OCR in R:

github.com/duncantl/Rtesseract

Getting everything to work is quite difficult and the documentation isn't fantastic but Tesseract is very very powerful.  Maybe worth a look or even merging together.  If it gets far enough I have my own functions for converting PDFs to TIFS or be read into tesseract if it gets that far.  Regardless another great package Scott/Opensci team - big thanks for all your amazing work.

**Comment by sckott** [comment]
@abresler thanks for bringing this up

I started playing with a separate package to just do extraction from PDFs `extract`, and we have an open issue there for tesseract  https://github.com/sckott/extract/issues/5 - thx for pointing out duncan's pkg, i didn't know about that.  

I think tesseract does fit in here, but only in the sense that we'll get it in extract, then import here as an option for users

**Comment by sckott** [comment]
@jeroenooms is working on a wrapper https://github.com/jeroenooms/tesseract - is it useable yet Jeroen?

**Comment by sckott** [comment]
closing this here, we'll use J's package once it ready inside `extract` pkg probably, then use that here
