### ISSUE TITLE
Grabbing supplementary data from articles

### ISSUE THREAD

**Issue by willpearse** [ropensci/fulltext#61]
I've been idly messing around with a [package to pull out SI from papers (grabr) and load their data (phylogenies, CSVs, etc.) directly into R](https://github.com/willpearse/grabr/). It's not very clever, but it does work for quite a few journals and publishers (PLoS, Wiley, Figshare, some others) and I really like using it (who doesn't like their own code? :p).

Is this the sort of thing you'd like in fulltext? If so, I'll clean up and pull request. If not... no problem. I feel like someone grabbing text from an article might also want to grab the data that led to the article being written, but I'm happy to be disagreed with :D

**Comment by sckott** [comment]
@willpearse Good idea - I don't think we've accounted for this, we've just focused on the text of the article. 

I think it could fit in - perhaps as a function, or set of functions, that focus on fetching supplementary files. 

Thoughts on fit @karthik @dwinter @cboettig @jennybc @richfitz

**Comment by sckott** [comment]
Looks like we've discussed this use case before https://github.com/ropensci/fulltext/issues/3#issuecomment-52423692

@willpearse if you're okay sending a PR here, that'd be great, best if it would work like the other functions (e.g., if a user searchers for articles, then they could easily pass that output to your function(s) to get supp data [e.g. https://github.com/ropensci/fulltext/blob/master/R/ft_get.R#L157-L158])

**Comment by willpearse** [comment]
OK, thanks. I don't have a feeling for whether that's trivial or not
off-hand, but I'll take a look. Expect something from me in the next few
days...

**Comment by sckott** [comment]
Woops, didn't mean to close, reopened. 

Sounds good
