### ISSUE TITLE
Package name change

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#72]
This package name makes sense in that it does what it says in the name, but it's super hard to search for on google/github/etc. I think ideally we should have something that is meaningful, but more importantly unique and not a common word so we can easily find mention of its use. There is the issue of changing name on CRAN, but i think it's worth it. it's still early days

other options:

* `prospectr` - only 15K results on google and about [1,400 hits on github](https://github.com/search?utf8=%E2%9C%93&q=prospectr&type=Code&ref=searchresults) - spelled wrong of course to reduce conflict with similar words

anyone have other ideas?

**Comment by karthik** [comment]
I agree with the general idea. Something close to the general purpose would still be helpful. Prospectr could apply to just about anything.

**Comment by sckott** [comment]
* `leximiner` - play on lexicon - only 5 results on google scholar

**Comment by sckott** [comment]
@dwinter @willpearse what do you think about the name `leximiner`  (or `lexminer`)

**Comment by willpearse** [comment]
Personally, I liked ```fulltext``` and the package has already got downloads as that, so I'm not 100% behind changing. That said, I'm not the lead, so I'm happy with whatever you're happy with.

My comment would be that ```leximiner``` doesn't cover the downloading of SI, which is both one of the use cases and is the reason we're pushing to get a new version on CRAN. The same could, of course, be said for ```fulltext```, so from that perspective it's an even swap.

Is there anything wrong with ```grabr```? I would delete my GitHub repo to make things clearer...

**Comment by sckott** [comment]
Yeah, it's less good now to change name that it's on CRAN.  Right, I guess my proposed name doesn't seem to include supplementary materials.  `grabr` is a good name. Maybe it's best to stock with the current name. lets do that
