### ISSUE TITLE
Serialize function

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#8]
- ~~from xml to json~~
- ~~json to xml~~ (don't support this)
- ~~to list~~
- to data.frame (maybe, maybe not?)
- to zip/tar.gz?
- ~~to disk~~
- ~~to `tm` corpus~~ (done in ft_extract_corpus)

**Comment by sckott** [comment]
been playing with this via `Sxslt` , but of course this is only on Omegahat.  Looks like we use it in `RNeXML` - but as a Suggest.  I have gotten serializing XML to HTML via `xsltApplyStyleSheet()` but this probably isn't the most useful serialization.    

```r
library("fulltext")
library("Sxslt")
x <- ft_get('10.1371/journal.pone.0086169', from="plos")
xml <- xmlParse(x$plos$data$`10.1371/journal.pone.0086169`)
xsltApplyStyleSheet(xml, "~/Downloads/ViewNLM-v2.3/ViewNLM-v2.3.xsl")
```

gives https://gist.github.com/sckott/805fc7e97fe1b34daff1

**Comment by sckott** [comment]
@cboettig Or do you think it's worth it to import `Sxslt` to be able to use stylesheets?

**Comment by cboettig** [comment]
CRAN has been pretty happy with the Sxslt dependency; I've gotten more
trouble for github dependencies. Perhaps Duncan could be persuaded to put a
copy of Sxslt on CRAN if enough packages are using it.  (We use it in EML
too)

**Comment by sckott** [comment]
Perhaps use this https://github.com/hrbrmstr/xslt for any xslt work, should be a thing on cran at some point

**Comment by sckott** [comment]
Moving to milestone `v0.2`  - we have a working fxn, but I imagine will need more work to be stable/robust

**Comment by sckott** [comment]
closing for now, open issues as needed for fixes/features
