### ISSUE TITLE
BMC API down, need to rework using Springer API

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#81]
docs: https://dev.springer.com/documentation

**Comment by benmarwick** [comment]
Is this related?

```
> t_test <- ft_search(query = 't-test', from = 'bmc')
Error in tt$entries : $ operator is invalid for atomic vectors
```

**Comment by sckott** [comment]
yeah, i really need to get this sorted out asap :)

**Comment by sckott** [comment]
i think i got search fixed, but fetching articles is a hot mess because they recently merged into Springer, and now things are changed again and doesn't look like there's any XML provided. Looks like we can get XML via

* their FTP server at ftp://ftp.biomedcentral.com/articles/ - e.g., ftp://ftp.biomedcentral.com/articles/2049-2618-2-7.xml - though doesn't look like they have recent papers in their (.e.g, no 2016 papers in there)
* via their OAI service at http://www.biomedcentral.com/oai/2.0/ - looking into this

**Comment by sckott** [comment]
@benmarwick okay, can try again after installing from a new branch `devtools::install_github("ropensci/fulltext@bmc-fix")`

search is fixed, but not fetch `ft_get`

**Comment by benmarwick** [comment]
I'm getting 'Error: you need a user name for the Springer/BMC API'... How might I proceed?

**Comment by sckott** [comment]
let me check

**Comment by sckott** [comment]
@benmarwick okay, try again after re-installing, BMC is inside springer now, and they require an API key, added a new param to pass in a key, though not needed when not searching BMC

**Comment by sckott** [comment]
I'm going to remove BMC as an option from `ft_get` for now - They are a hot mess, esp. now that they are within Springer, - can't seem to find XML for papers anymore, and Springer has a maze of URLs from the landing article page to get to a pDF, maybe will add back later.
