### ISSUE TITLE
ft_get_si figshare broken i think

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#85]
@willpearse 

e.g., this url https://figshare.com/articles/Catching_crabs_a_case_study_in_local_scale_English_conservation/979288

the internal functions to get the urls for the files seem to be broken. I imagine they've reworked those pages. they know have a blob of JSON at the bottom e,g, could do this

```r
url <- "http://dx.doi.org/10.6084/m9.figshare.979288"
html <- xml2::read_html(content(GET(url), "text"))
jsonlite::fromJSON(xml2::xml_text(xml2::xml_find_one(html, "//script[@type=\"text/json\"]")))$article$files
```

**Comment by willpearse** [comment]
Thanks for this. I'm snowed under right now, so it may be a few days before I get to it. It looks very fixable - thanks for the suggestion :D

**Comment by sckott** [comment]
cool
