### ISSUE TITLE
In ft_search dplyr rbind_all deprecated use bind_rows message.

### ISSUE THREAD

**Issue by poldham** [ropensci/fulltext#89]
Hi Scott, 

In case you haven't spotted it yet, rbind_all is now deprecated and ft_search is producing the following error.

res <- ft_search(query='ecology', from=c('plos','crossref','arxiv'))
Error: `rbind_all()` is deprecated. Please use `bind_rows()` instead.
In addition: Warning message:
`rbind_all()` is deprecated. Please use `bind_rows()` instead. 

I think the same issue is also arising in rcrossref. 

All the best, 
Paul

**Comment by sckott** [comment]
Thanks for the report @poldham - I'll get this sorted out, and the rcrossref thing

**Comment by sckott** [comment]
@poldham what's your session info?

**Comment by poldham** [comment]
Scott it is

RStudio (preview) Version 0.99.1259 

Session info is

R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
character(0)

other attached packages:
[1] dplyr_0.5.0

loaded via a namespace (and not attached):
[1] rsconnect_0.4.3 graphics_3.3.1  tools_3.3.1    
[4] utils_3.3.1     grDevices_3.3.1 stats_3.3.1    
[7] datasets_3.3.1  methods_3.3.1   base_3.3.1

**Comment by sckott** [comment]
Can you edit above with session info for after you load `fulltext`

**Comment by sckott** [comment]
that may be coming from a a number of different `fulltext` dependencies

**Comment by poldham** [comment]
Here you go. I compared the fulltext dependencies with those of rcrossref (0.5.2) and the only difference I can see is rcrossref as a dependency in fulltext. That suggests that maybe it is rcrossref as the source. rcrossref session info pasted below fulltext.

> sessionInfo(package = "fulltext")
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.5 (Yosemite)
> 
> locale:
> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
> 
> attached base packages:
> character(0)
> 
> other attached packages:
> [1] fulltext_0.1.6
> 
> loaded via a namespace (and not attached):
>  [1] NLP_0.1-9         Rcpp_0.12.5       plyr_1.8.4       
>  [4] R.methodsS3_1.7.1 methods_3.3.1     R.utils_2.3.0    
>  [7] utils_3.3.1       tools_3.3.1       grDevices_3.3.1  
> [10] digest_0.6.9      jsonlite_1.0      lubridate_1.5.6  
> [13] tibble_1.1        gtable_0.2.0      R.cache_0.12.0   
> [16] rcrossref_0.5.2   aRxiv_0.5.10      bibtex_0.4.0     
> [19] DBI_0.4-1         parallel_3.3.1    dplyr_0.5.0      
> [22] httr_1.2.1        stringr_1.0.0     xml2_1.0.0       
> [25] graphics_3.3.1    datasets_3.3.1    stats_3.3.1      
> [28] rredis_1.7.0      grid_3.3.1        base_3.3.1       
> [31] R6_2.1.2          rentrez_1.0.2     XML_3.98-1.4     
> [34] ggplot2_2.1.0     reshape2_1.4.1    solr_0.1.6       
> [37] magrittr_1.5      whisker_0.3-2     rplos_0.5.6      
> [40] scales_0.4.0      rsconnect_0.4.3   assertthat_0.1   
> [43] colorspace_1.2-6  stringi_1.1.1     munsell_0.4.3    
> [46] slam_0.1-35       tm_0.6-2          rjson_0.2.15     
> [49] R.oo_1.20.0      

RCROSSREF Session Info

sessionInfo(package = "rcrossref")
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
character(0)

other attached packages:
[1] rcrossref_0.5.2

loaded via a namespace (and not attached):
 [1] NLP_0.1-9         Rcpp_0.12.5       plyr_1.8.4       
 [4] R.methodsS3_1.7.1 methods_3.3.1     R.utils_2.3.0    
 [7] utils_3.3.1       tools_3.3.1       grDevices_3.3.1  
[10] digest_0.6.9      jsonlite_1.0      lubridate_1.5.6  
[13] tibble_1.1        gtable_0.2.0      R.cache_0.12.0   
[16] aRxiv_0.5.10      bibtex_0.4.0      DBI_0.4-1        
[19] parallel_3.3.1    dplyr_0.5.0       httr_1.2.1       
[22] stringr_1.0.0     xml2_1.0.0        graphics_3.3.1   
[25] datasets_3.3.1    stats_3.3.1       rredis_1.7.0     
[28] grid_3.3.1        base_3.3.1        R6_2.1.2         
[31] rentrez_1.0.2     XML_3.98-1.4      ggplot2_2.1.0    
[34] reshape2_1.4.1    solr_0.1.6        magrittr_1.5     
[37] whisker_0.3-2     rplos_0.5.6       scales_0.4.0     
[40] rsconnect_0.4.3   assertthat_0.1    colorspace_1.2-6 
[43] stringi_1.1.1     munsell_0.4.3     slam_0.1-35      
[46] tm_0.6-2          rjson_0.2.15      R.oo_1.20.0

**Comment by poldham** [comment]
Ok many thanks, happy to download and test as planning to demo this in some training next week.

**Comment by sckott** [comment]
@poldham `rcrossref` was sent to CRAN about 1 hr ago, install `fulltext` from Github and it should install dev `rcrossref` from github since we're using `Remotes` in descriptino file

**Comment by sckott** [comment]
on CRAN just now, binaries should all be up sometime tomorrow probably

**Comment by poldham** [comment]
Thanks Scott, 

Downloaded dev version as not on cran yet. crossref now seems ok. Note that rbind_all issue also occurs in rplos pkg

rplos example

pizza <- rplos::searchplos(q = "pizza", fl = c("id","publication_date", "title", "abstract"), limit = 20)
Warning: `rbind_all()` is deprecated. Please use `bind_rows()` instead.

fulltext example

res1 <- ft_search(query='ecology', from='plos')
Warning message:
`rbind_all()` is deprecated. Please use `bind_rows()` instead. 

res2 <- ft_search(query='ecology', from='crossref’)

**Comment by sckott** [comment]
thanks, and right, fixed in https://github.com/ropensci/rplos/issues/105, not on CRAN yet though - i'll push that one to CRAN as well

**Comment by sckott** [comment]
@poldham Okay, `rplos` off 2 CRAN just now - anything else?

**Comment by poldham** [comment]
All good I think Scott. Many thanks! Paul

**Comment by sckott** [comment]
okay, thanks

**Comment by sckott** [comment]
rplos on CRAN now, binaries within a day or so
