### ISSUE TITLE
Issue when retrieving recently publised data

### ISSUE THREAD

**Issue by fgabriel1891** [ropensci/fulltext#93]
I'm getting this error message when using the ft_get function. I'm trying to download all the articles passed from ft_search and I get the following: 

Error: `out$headers$`content-type` == "text/xml"` is not TRUE

I pass the function to the list of DOI's with a loop to identify if the problem is a determined DOI and the function got stuck in this particular publication

10.1371/journal.pone.0166824; which is published very recently. As I'm working on a project I had to run the same code the week ago without a problem and without the need for a loop. The problem has arisen just this week, exactly a day after the publication of that particular article.

**Comment by sckott** [comment]
thanks @fgabriel1891 for your report - does appear to be a bug at least with that DOI. any more problems with other DOIs?

**Comment by fgabriel1891** [comment]
No, I downloaded 100+ articles without a problem once I erased that
particular DOI from my list to download.

BTW, excellent work with this and all ropensci packages, are of much help
to implement a "semi - automated mining of species interactions from
literature" for my research. Congrats!

Best,
Gabriel


2016-11-23 17:47 GMT+01:00 Scott Chamberlain <notifications@github.com>:

**Comment by sckott** [comment]
@fgabriel1891 thanks for the kind words!

have to make a fix in a dependency package `rplos` - going to submit to CRAN today, but in meantime, you can install from github `devtools::install_github("ropensci/rplos")` and it should work for you now

**Comment by fgabriel1891** [comment]
Thanks! 

New update: With the CRAN version I found the same issue with this DOI http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0163338, again recently published in PLOS. 

I will install the git-hub version to test it

**Comment by sckott** [comment]
thanks, that one works with the new version

**Comment by fgabriel1891** [comment]
Yeap, it works :) Many thanks!!

**Comment by sckott** [comment]
new rplos sent to cran
