### ISSUE TITLE
ft_abstact: for abstracts

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#98]
- [x] scopus
- [x] microsoft
- [x] crossref
- [x] plos
- [ ] maybe europe pmc

others i don't think make sense

**Comment by sckott** [comment]
related to #99

**Comment by andreifoldes** [comment]
Hi there - wouldn't this be useful for crossref as well? They have abstract in some cases don't they?

**Comment by sckott** [comment]
@andreifoldes right, they do sometimes have abstracts. as of right now, looks like Crossref has ~1% of papers with abstracts, though that's still about 1.5 million, so probably worth doing. I'll work on adding it in.

**Comment by sckott** [comment]
@andreifoldes reinstall `devtools::install_github("ropensci/fulltext")` and see the docs for `ft_abstract`

**Comment by sckott** [comment]
closing, good for now
